
before_script:
    - git clone -q --depth 1 https://gitlab.com/voxl-public/voxl-sdk/ci-tools


# Build for the qrb5165 1.X (18.04) and 2.X (20.04) system images

include:
  - project: 'voxl-public/voxl-sdk/ci-tools'
    file: '/pipeline-configs/common.yml'
  - project: 'voxl-public/voxl-sdk/ci-tools'
    file: '/pipeline-configs/cross-qrb5165.yml'
  
variables:
    GIT_SUBMODULE_STRATEGY: recursive

